### ISSUE TITLE
[Bug] no channel or video displayed

### ISSUE THREAD

**Issue by carnager** [kuylar/lighttube#65]
### Describe the bug

I installed lighttube using docker-compose.
I extracted the refresh_token and used it in the `- LIGHTTUBE_AUTH_REFRESH_TOKEN=` config option.

When I try to visit a channel, I get this:

```
lightube-lighttube-1  | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
lightube-lighttube-1  |       An unhandled exception has occurred while executing the request.
lightube-lighttube-1  |       System.AggregateException: One or more errors occurred. (The format of value ' ' is invalid.)
lightube-lighttube-1  |        ---> System.FormatException: The format of value ' ' is invalid.
lightube-lighttube-1  |          at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
lightube-lighttube-1  |          at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
lightube-lighttube-1  |          at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
lightube-lighttube-1  |          at InnerTube.InnerTube.MakeRequest(RequestClient client, String endpoint, InnerTubeRequest postData, String language, String region, Boolean authorized)
```

**Comment by kuylar** [comment]
This bug took way too long to spot, gonna have a docker image ready in ~15 minutes (the current `:20230720` doesn't have this fix, its gonna be overwritten)
