### ISSUE TITLE
[Bug] The video player won't load

### ISSUE THREAD

**Issue by c0lbarator** [kuylar/LightTube#88]
### Describe the bug

I'm running a local instance of lighttube and when I click on a link to a video I get a player window with this error. Can you please tell me how to fix this?
    LightTube instance this error occured on (127.0.0.1:7134)
    LightTube & InnerTube versions (2023.9.24 / 1.0.25.0)
    The full resource path (/watch?v=n4-w7xXJtfc)
    InnerTube language & region (en_US)
    The following text (the whole thing):

System.AggregateException: One or more errors occurred. (Request failed (status code: 401 (Unauthorized))) (Request failed (status code: 401 (Unauthorized)))
---> InnerTube.Exceptions.RequestException: Request failed (status code: 401 (Unauthorized))
at InnerTube.InnerTube.MakeRequest(RequestClient client, String endpoint, InnerTubeRequest postData, String language, String region, Boolean authorized)
at InnerTube.InnerTube.GetPlayerObjectAsync(String videoId, Boolean contentCheckOk, String language, String region, RequestClient client)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
at InnerTube.InnerTube.GetPlayerAsync(String videoId, Boolean contentCheckOk, Boolean includeHls, String language, String region)
---> (Inner Exception #1) InnerTube.Exceptions.RequestException: Request failed (status code: 401 (Unauthorized))
at InnerTube.InnerTube.MakeRequest(RequestClient client, String endpoint, InnerTubeRequest postData, String language, String region, Boolean authorized)
at InnerTube.InnerTube.GetPlayerObjectAsync(String videoId, Boolean contentCheckOk, String language, String region, RequestClient client)<---

**Comment by kuylar** [comment]
Can you provide some information about your configuration? for example

- Are you using `cookie` or `oauth2` as your `LIGHTTUBE_AUTH_TYPE`?
- Have you tried changing your auth credentials and tried again?
- Does this error happen on one video or just the one you linked

**Comment by c0lbarator** [comment]
- I am using oauth2
- I tried using different auth credentials
- This error happen on all videos

**Comment by kuylar** [comment]
Are you sure you followed the steps in [the InnerTube wiki](https://github.com/kuylar/InnerTube/wiki/Authorization#using-a-refresh-token)? Because from my testing this error would only be generated if you were using another OAuth application than YouTube TV, since the client ID's and secrets don't match

**Comment by c0lbarator** [comment]
I followed the steps from wiki, I got refresh_token from youtube tv site, tried using different IPs and accounts, but got similar results, sometimes I also got 400 bad request error

**Comment by c0lbarator** [comment]
Sorry, I forgot to remove the lines for cookie auth, now player works!
